- headers-ext/src/common/connection.rs
I couldn't find where the spec says that they should be case-insensitive, but warp's websocket filter looks for `upgrade` while e.g. Chrome sends `Upgrade`, so the warp websocket doesn't work anymore with Chrome since I upgraded to 0.1.6.
> Compare Connection header values case-insensitively

- headers-core/src/lib.rs
- headers-derive/src/lib.rs
- src/common/accept_ranges.rs
- src/common/access_control_allow_credentials.rs
- src/common/access_control_request_method.rs
- src/common/authorization.rs
- src/common/cache_control.rs
- src/common/content_disposition.rs
- src/common/content_length.rs
- src/common/content_range.rs
- src/common/content_type.rs
- src/common/expect.rs
- src/common/host.rs
- src/common/mod.rs
- src/common/proxy_authorization.rs
- src/common/range.rs
- src/common/sec_websocket_version.rs
- src/common/set_cookie.rs
- src/common/strict_transport_security.rs
- src/lib.rs
(Note: this PR builds off #32. The diff is noisier than it would be otherwise.)
Anyways: this PR changes the `Header` trait's `const NAME: &'static HeaderName` to a `fn name() -> &'static HeaderName`. Therefore, the header trait now looks like:
```rust
pub trait Header {
/// The name of this header.
fn name() -> &'static HeaderName;
/// Decode this type from an iterator of `HeaderValue`s.
fn decode<'i, I>(values: &mut I) -> Result<Self, Error>
where
Self: Sized,
I: Iterator<Item = &'i HeaderValue>;
/// Encode this type to a `HeaderMap`.
///
/// This function should be infallible. Any errors converting to a
/// `HeaderValue` should have been caught when parsing or constructing
/// this value.
fn encode<E: Extend<HeaderValue>>(&self, values: &mut E);
}
```
This makes supporting custom typed …
> Change `name` from const to method

- headers-core/src/lib.rs
Otherwise, it's impossible to interoperate with a function returning
`Result<_, Box<Error + ...>>`
> Implement std::error::Error for Error

- src/common/access_control_allow_credentials.rs
The spec says that the value passed here should be case sensitive thus
True shouldn't be a valid value. See
https://fetch.spec.whatwg.org/#ref-for-http-access-control-allow-credentials
> Make Access-Control-Allow-Credentials case sensitive

- Cargo.toml
This helps with `-Z minimal-versions` builds. Yeah, this option is kind of a meme, but doesn't stop me from suggesting improvements.
> Increase dependency versions to real minimal versions

- src/common/referer.rs
Fixes this warning:
```
warning: unresolved link to `sic`
--> src/common/referer.rs:8:20
|
8 | /// The `Referer` [sic] header field allows the user agent to specify a
|                    ^^^ no item named `sic` in scope
|
= note: `#[warn(broken_intra_doc_links)]` on by default
= help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
```
> Escape [sic] in docs (not an intra doc link)

- .github/workflows/ci.yml
- src/common/access_control_allow_origin.rs
There is currently no way to build an `AccessControlAllowOrigin` with an actual origin value that isn't `Any` or `Null`. This PR adds a TryFrom trait to that header to fix this.
I added a line in the doctest and an additional test to cover this new trait.
~~It's a bit of an ugly implementation, because the only way to build an `OriginOrAny` at present is to `try_from_values` with an iterator.~~
> add TryFrom for AccessControlAllowOrigin

- src/common/authorization.rs
"Smaller" variation of #100 that provides _most_ of the same benefits.
> Add forwarding methods to Authorization<C> for provided C's

- Cargo.toml
The RustCrypto project recently got control of the crate name `sha1`. This
commit switches over to the new name; the old `sha-1` name is now deprecated.
Details: https://github.com/RustCrypto/hashes/pull/350
> Switch from `sha-1` to `sha1`

- .github/workflows/ci.yml
Fixes the MSRV job by bumping to 1.51 as required by the `sha1` crate
> Bump MSRV to 1.51

- src/common/cache_control.rs
I found the docs a bit confusing/inconsistent here (https://docs.rs/headers/0.3.8/headers/struct.CacheControl.html#method.with_max_age) since Duration needn't be specified in seconds.
> s/seconds/duration in variable name to CacheControl

- .github/workflows/ci.yml
- src/common/content_range.rs
- src/common/etag.rs
- src/common/host.rs
- src/common/if_range.rs
- src/common/origin.rs
- src/util/entity.rs
- src/util/flat_csv.rs
Grabbed the incantation from
https://github.com/hyperium/hyper/blob/master/.github/workflows/CI.yml
Was noticing that my editor was automatically doing this - and figured it's good form to use an autoformatter with default settings.
> Add cargo fmt --check to CI

- src/common/cache_control.rs
RFC8246 adds this https://www.rfc-editor.org/rfc/rfc8246. Reasonable documentation here
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
> Add immutable flag to CacheControl

- .github/workflows/ci.yml
- Cargo.toml
Necessary as httpdate 1.0.3 introduced MSRV, choosing 1.56
> Raise msrv to 1.56

- Cargo.toml
- src/common/authorization.rs
- src/common/sec_websocket_accept.rs
Also added once_cell for caching the new Engine based APIs of base64
Signed-off-by: Ayush Singh <ayushsingh1325@gmail.com>
> Update base64 to 0.21

- src/common/cache_control.rs
While working with Cache Control on another project, I noticed that the "must-understand" directive was missing.
I followed along the lines of a previous contribution, let me know if there's anything that is missing or incorrect and I'll be glad to work it through.
> Add support for "must-understand" directive

- src/common/authorization.rs
Closes https://github.com/hyperium/headers/pull/141. (Based on this PR, but moved to using [`std::slice::eq_ignore_ascii_case()`](https://doc.rust-lang.org/std/primitive.slice.html#method.eq_ignore_ascii_case) which doesn't allocate or copy.)
Partially addresses https://github.com/hyperium/headers/issues/112. (Does not validate that e.g. the token part of `Bearer token` contains valid token68 characters, however.)
> Make authorization schemes case and whitespace insensitive

- src/common/range.rs
An HTTP Range of `bytes=-100` means a suffix, the last 100 bytes. This was wrongly parsed as the Rust range `..100`, which means the first 100 bytes.
This has been fixed, but doing so required change `Range::iter` to accept a length argument, to determine if the ranges are satisfiable.
Closes #87 
BREAKING CHANGE: Change `.iter()` calls to `.satisfiable_ranges(len)`.
Also, the `Range::bytes()` constructor will now return an error if
pass a `RangeTo` (e.g. `Range::bytes(..100)`).
> fix: Range suffixes are not Rust RangeTo

- src/common/referer.rs
Based on #95, but just adds impl Display
> Implement Display for Referer

- src/common/content_encoding.rs
Allows easy construction of a `Content-Encoding` header of type `br` (Brotli compression algorithm)
> Add `ContentEncoding::brotli`

- headers-core/src/lib.rs
`Header`'s `encode` method seems to convert the receiver to `HeaderValue`.
>  doc(core): Header encode method convert header to HeaderValue

- Cargo.toml
> chore: update to base64 0.22

- .github/workflows/ci.yml
- headers-core/Cargo.toml
Sets `headers-core`'s msrv to 1.49, the same version of `http` which is the only crate `headers-core` depends on.
> chore(core): set msrv to 1.49

- src/common/accept_ranges.rs
Adds `AcceptRanges` none util.
> feat: add AcceptRanges none util

- src/lib.rs
Re-exports `mime::Mime`. This struct has already been an external type as [`ContentType`](https://docs.rs/headers/latest/headers/struct.ContentType.html#). Especially when users convert from `Mime` to `ContentType`, this would be useful.
> feat: re-export mime::Mime

- src/common/content_encoding.rs
Same as #158 but for zstd, which is currently available in Firefox and Chromium based browsers [^1] and `reqwest` [^2]
[^1]: https://caniuse.com/zstd
[^2]: https://github.com/seanmonstar/reqwest/pull/1866
> Add `ContentEncoding::zstd`

- src/common/cache_control.rs
The `must-revalidate` flag is supported. This adds the methods to test for its existence in and/or to add it to `CacheControl`.
Fixes #189.
> Add methods for `must-revalidate` flag to `CacheControl`

- src/common/cache_control.rs
- src/common/connection.rs
- src/common/content_encoding.rs
- src/common/content_range.rs
- src/common/strict_transport_security.rs
- src/map_ext.rs
> refactor: Remove needless lifetime

- src/common/mod.rs
Closes #195. On this branch, the command `cargo +nightly bench --features nightly` can now be run without any compiler errors.
> fix(tests): Fix test compile error with nightly feature

- src/disabled/warning.rs
> chore: remove redundant word
